import {
  RecognizedObjectCalibration,
  FenceCalibrationScenario,
  SafetyFenceZone,
} from './types';

export const RECOGNIZED_OBJECT_CATALOG: RecognizedObjectCalibration[] = [
  {
    id: 'obj_worker_certified',
    name: '合规持证作业人员 (Authorized Worker)',
    code: 'WORKER_CERTIFIED',
    category: 'personnel',
    color: '#52c41a',
    description: '通过人脸识别与 PPE 穿戴检测认证，穿戴安全帽、反光背心及防静电手环',
    defaultAllowedZones: ['ZONE_PEDESTRIAN_LANE', 'ZONE_CORRIDOR_SHARED'],
    mandatoryPPE: ['HELMET', 'SAFETY_SHOES', 'ESD_STRAP'],
    riskLevel: 'low',
  },
  {
    id: 'obj_worker_no_ppe',
    name: '未佩戴安全防护违规人员 (Unprotected Worker)',
    code: 'WORKER_NO_PPE',
    category: 'personnel',
    color: '#ff4d4f',
    description: '未识别到反光条或安全帽，属于高风险闯入目标，进入防区即刻告警并联锁停机',
    defaultAllowedZones: [],
    riskLevel: 'high',
  },
  {
    id: 'obj_agv_tugger',
    name: 'AGV / AMR 物流小车 (Automated Vehicle)',
    code: 'AGV_TUGGER',
    category: 'vehicle',
    color: '#1890ff',
    description: '地面磁条或激光 SLAM 导航物流小车，限定在 AGV 专属物料通廊内运行',
    defaultAllowedZones: ['ZONE_AGV_LANE', 'ZONE_CORRIDOR_SHARED'],
    riskLevel: 'medium',
  },
  {
    id: 'obj_forklift',
    name: '重载叉车 / 物料牵引车 (Heavy Forklift)',
    code: 'FORKLIFT',
    category: 'vehicle',
    color: '#faad14',
    description: '有人驾驶载重叉车，盲区范围大，禁止侵入人行绿色安全斑马线',
    defaultAllowedZones: ['ZONE_AGV_LANE'],
    riskLevel: 'high',
  },
  {
    id: 'obj_robot_arm',
    name: '六轴工业协作/焊接机械臂 (Robotic Arm)',
    code: 'ROBOT_ARM',
    category: 'equipment',
    color: '#722ed1',
    description: '高速重载回转机械臂，包络线半径内属于 Cat-4 极限危险区域',
    defaultAllowedZones: ['ZONE_ROBOT_WORKCELL'],
    riskLevel: 'high',
  },
  {
    id: 'obj_foreign_hazard',
    name: '异物遗留 / 跌落工具 (Foreign Tool / Hazard)',
    code: 'FOREIGN_OBJECT',
    category: 'foreign_hazard',
    color: '#eb2f96',
    description: '遗留在传送带或轨道上的扳手、螺丝刀、托盘碎屑等非受控外来异物',
    defaultAllowedZones: [],
    riskLevel: 'high',
  },
];

export const SAFETY_SCENARIOS: Record<string, FenceCalibrationScenario> = {
  robot_welding_cell: {
    id: 'robot_welding_cell',
    name: '六轴激光点焊机器人安全工作岛 (Robotic Cell)',
    industry: '汽车装备 / 重工制造',
    cameraFov: '7500mm × 5000mm 俯视',
    resolution: '3840×2160 (4K@60FPS)',
    description:
      '工业级机器人安全标准 (ISO 10218-1 / ISO 13849-1 PL-e)。配置外围 Cat-1 预警减速防区与核心 Cat-4 极限回转急停防区，实时防止人员误入激光焊接弧光与机械臂挤压区。',
    defaultFences: [
      {
        id: 'fence_cat4_core',
        name: '机械臂回转极限危险防区 (Cat-4 E-Stop)',
        code: 'ZONE_ROBOT_WORKCELL',
        fenceType: 'polygon',
        dangerLevel: 'cat4_estop',
        color: '#ff4d4f',
        enabled: true,
        points: [
          { x: 260, y: 70 },
          { x: 570, y: 70 },
          { x: 590, y: 360 },
          { x: 240, y: 360 },
        ],
        triggerAnchor: 'bottom_center',
        direction: 'bidirectional',
        dwellTimeSec: 0.1,
        safetyBufferPx: 25,
        allowedClassCodes: ['ROBOT_ARM'],
        blockedClassCodes: ['WORKER_CERTIFIED', 'WORKER_NO_PPE', 'FOREIGN_OBJECT'],
        hardwareAction: {
          estopRelay: true,
          slowdownSignal: false,
          andonColor: 'red',
          buzzerSound: true,
          plcModbusCoil: '0x0010 (Emergency Stop PLe Relay)',
        },
      },
      {
        id: 'fence_cat2_buffer',
        name: '人机交互减速缓冲区 (Cat-2 Slowdown)',
        code: 'ZONE_BUFFER_SLOWDOWN',
        fenceType: 'polygon',
        dangerLevel: 'cat2_slowdown',
        color: '#faad14',
        enabled: true,
        points: [
          { x: 190, y: 40 },
          { x: 630, y: 40 },
          { x: 650, y: 390 },
          { x: 170, y: 390 },
        ],
        triggerAnchor: 'center',
        direction: 'inbound',
        dwellTimeSec: 0.3,
        safetyBufferPx: 40,
        allowedClassCodes: ['ROBOT_ARM'],
        blockedClassCodes: ['WORKER_CERTIFIED', 'WORKER_NO_PPE'],
        hardwareAction: {
          estopRelay: false,
          slowdownSignal: true,
          andonColor: 'amber',
          buzzerSound: false,
          plcModbusCoil: '0x0011 (Robot 20% Speed Override)',
        },
      },
      {
        id: 'fence_pedestrian_path',
        name: '合规操作员人行通道 (Pedestrian Walkway)',
        code: 'ZONE_PEDESTRIAN_LANE',
        fenceType: 'polygon',
        dangerLevel: 'cat1_warning',
        color: '#52c41a',
        enabled: true,
        points: [
          { x: 30, y: 50 },
          { x: 140, y: 50 },
          { x: 140, y: 380 },
          { x: 30, y: 380 },
        ],
        triggerAnchor: 'center',
        direction: 'bidirectional',
        dwellTimeSec: 1.0,
        safetyBufferPx: 10,
        allowedClassCodes: ['WORKER_CERTIFIED'],
        blockedClassCodes: ['WORKER_NO_PPE', 'FORKLIFT'],
        hardwareAction: {
          estopRelay: false,
          slowdownSignal: false,
          andonColor: 'amber',
          buzzerSound: false,
          plcModbusCoil: '0x0012 (Pedestrian Gate Lock)',
        },
      },
    ],
    defaultObjects: [
      {
        id: 1,
        trackId: 101,
        code: 'ROBOT_ARM',
        label: 'Kuka 点焊机械臂',
        x: 390,
        y: 180,
        w: 110,
        h: 110,
        vx: 0,
        vy: 0,
        confidence: 0.992,
        inDangerZone: false,
      },
      {
        id: 2,
        trackId: 102,
        code: 'WORKER_NO_PPE',
        label: '未戴安全帽人员 (高危)',
        x: 210,
        y: 140,
        w: 60,
        h: 100,
        vx: 0.5,
        vy: 0.3,
        confidence: 0.946,
        inDangerZone: true,
      },
      {
        id: 3,
        trackId: 103,
        code: 'WORKER_CERTIFIED',
        label: '持证巡检工 (合规)',
        x: 60,
        y: 190,
        w: 55,
        h: 95,
        vx: 0,
        vy: 0.8,
        confidence: 0.981,
        inDangerZone: false,
      },
    ],
  },

  agv_shared_corridor: {
    id: 'agv_shared_corridor',
    name: 'AGV / AMR 与人车混行物流通道 (Intralogistics Corridor)',
    industry: '仓储物流 / 3C 制造',
    cameraFov: '12000mm × 6000mm 广角',
    resolution: '1920×1080 (FullHD@60FPS)',
    description:
      '智能仓储高频搬运场景，自动检测 AGV 物流小车是否偏出既定导引磁轨，同时标定人员横穿斑马线虚拟光幕 (Virtual Light Curtain)，自动计算制动停止距离。',
    defaultFences: [
      {
        id: 'fence_agv_transit',
        name: 'AGV 物流主轨道安全保护区',
        code: 'ZONE_AGV_LANE',
        fenceType: 'polygon',
        dangerLevel: 'cat2_slowdown',
        color: '#1890ff',
        enabled: true,
        points: [
          { x: 180, y: 40 },
          { x: 480, y: 40 },
          { x: 480, y: 380 },
          { x: 180, y: 380 },
        ],
        triggerAnchor: 'bottom_center',
        direction: 'bidirectional',
        dwellTimeSec: 0.2,
        safetyBufferPx: 20,
        allowedClassCodes: ['AGV_TUGGER'],
        blockedClassCodes: ['WORKER_CERTIFIED', 'WORKER_NO_PPE', 'FORKLIFT'],
        hardwareAction: {
          estopRelay: false,
          slowdownSignal: true,
          andonColor: 'amber',
          buzzerSound: true,
          plcModbusCoil: '0x0013 (AGV Emergency Decelerate)',
        },
      },
      {
        id: 'fence_tripwire_crossing',
        name: '行人横穿虚拟光幕触发线 (Line Tripwire)',
        code: 'LINE_CROSSING_CURTAIN',
        fenceType: 'line_tripwire',
        dangerLevel: 'cat4_estop',
        color: '#ff4d4f',
        enabled: true,
        points: [
          { x: 150, y: 220 },
          { x: 520, y: 220 },
        ],
        triggerAnchor: 'center',
        direction: 'inbound',
        dwellTimeSec: 0.05,
        safetyBufferPx: 15,
        allowedClassCodes: [],
        blockedClassCodes: ['WORKER_CERTIFIED', 'WORKER_NO_PPE'],
        hardwareAction: {
          estopRelay: true,
          slowdownSignal: false,
          andonColor: 'red',
          buzzerSound: true,
          plcModbusCoil: '0x0014 (Safety Optical Relay E-Stop)',
        },
      },
    ],
    defaultObjects: [
      {
        id: 11,
        trackId: 201,
        code: 'AGV_TUGGER',
        label: 'AGV-04 物流牵引车',
        x: 290,
        y: 70,
        w: 80,
        h: 65,
        vx: 0,
        vy: 1.8,
        confidence: 0.989,
        inDangerZone: false,
      },
      {
        id: 12,
        trackId: 202,
        code: 'WORKER_CERTIFIED',
        label: '操作工 (横穿中)',
        x: 170,
        y: 200,
        w: 55,
        h: 90,
        vx: 1.2,
        vy: 0.2,
        confidence: 0.963,
        inDangerZone: true,
      },
    ],
  },

  smt_feeder_safety: {
    id: 'smt_feeder_safety',
    name: 'SMT 高速贴片机飞达送料与回流炉安全防区',
    industry: '3C 电子制造 / SMT AOI',
    cameraFov: '4000mm × 3000mm',
    resolution: '2560×1440 (2K@60FPS)',
    description:
      '高速飞达料架高速往复运动区（防夹伤）与回流炉高温出口区（防烫伤）。实时识别手部或工具违规进入运动机械行程，毫秒级连锁伺服断电。',
    defaultFences: [
      {
        id: 'fence_feeder_carriage',
        name: '高速贴片头往复夹伤高危区',
        code: 'ZONE_SMT_FEEDER_DANGER',
        fenceType: 'polygon',
        dangerLevel: 'cat4_estop',
        color: '#ff4d4f',
        enabled: true,
        points: [
          { x: 220, y: 60 },
          { x: 580, y: 60 },
          { x: 580, y: 260 },
          { x: 220, y: 260 },
        ],
        triggerAnchor: 'hands_feet_pose',
        direction: 'inbound',
        dwellTimeSec: 0.05,
        safetyBufferPx: 20,
        allowedClassCodes: [],
        blockedClassCodes: ['WORKER_CERTIFIED', 'WORKER_NO_PPE', 'FOREIGN_OBJECT'],
        hardwareAction: {
          estopRelay: true,
          slowdownSignal: false,
          andonColor: 'red',
          buzzerSound: true,
          plcModbusCoil: '0x0015 (SMT Servo Power Cutoff)',
        },
      },
    ],
    defaultObjects: [
      {
        id: 21,
        trackId: 301,
        code: 'WORKER_CERTIFIED',
        label: '操作员双手 (伸手换料中)',
        x: 230,
        y: 190,
        w: 65,
        h: 95,
        vx: 0.3,
        vy: 0.1,
        confidence: 0.975,
        inDangerZone: true,
      },
    ],
  },
};
